# malice/pdf plugin configuration.

name = 'pdf'
description = 'PDF - tool to triage PDF documents'
category = 'doc'
version = '0.1.0'

accepts = [
    'document/pdf',
    'application/pdf'
    ]


[system]
cpu = 0.5
ram = 256 # MB

[settings]
max_size = 3000000 # 3 MB
max_extracted_file_count = 5 # Number of embedded files to extract
max_carved_file_size = 500 # Bytes (note: this might be tied to balbuzard.Pattern())
extract_limit = 10